export enum AddressMatchState {
    Confirmed = 'Y',
    NotConfirmed = 'N',
    SecondaryUnrecognized = 'S',
    SecondaryMissing = 'D'
}

export const AddressMatchStateNames: { [key in AddressMatchState]: string } = {
    [AddressMatchState.Confirmed]: 'Confirmed',
    [AddressMatchState.NotConfirmed]: 'NotConfirmed',
    [AddressMatchState.SecondaryUnrecognized]: 'SecondaryUnrecognized',
    [AddressMatchState.SecondaryMissing]: 'SecondaryMissing'
};

export enum DpvFootnote {
    StreetNameCityStateZipAllValid = 'AA',
    AddressNotPresentInUspsData = 'A1',
    EntireAddressIsValid = 'BB',
    SecondaryNotRecognizedSecondaryNotRequired = 'CC',
    SecondaryNotRecognizedSecondaryIsRequired = 'C1',
    MilitaryOrDiplomaticAddress = 'F1',
    GeneralDeliveryAddress = 'G1',
    PrimaryNumberIsMissing = 'M1',
    PrimaryNumberIsInvalid = 'M3',
    MissingRequiredSecondary = 'N1',
    PoBoxStyleAddress = 'PB',
    PoBoxNumberMissing = 'P1',
    PoBoxNumberInvalid = 'P3',
    ConfirmedWithPrivateMailboxInfo = 'RR',
    ConfirmedWithoutPrivateMailboxInfo = 'R1',
    ValidAddressThatDoesNotRecieveUspsDelivery = 'R7',
    PrimaryNumberMatchedByDroppingTrailingAlpha = 'TA',
    UniqueZipCode = 'U1',
}

export const DpvFootnoteNames: { [key in DpvFootnote]: string } = {
    [DpvFootnote.StreetNameCityStateZipAllValid]: 'StreetNameCityStateZipAllValid',
    [DpvFootnote.AddressNotPresentInUspsData]: 'AddressNotPresentInUspsData',
    [DpvFootnote.EntireAddressIsValid]: 'EntireAddressIsValid',
    [DpvFootnote.SecondaryNotRecognizedSecondaryNotRequired]: 'SecondaryNotRecognizedSecondaryNotRequired',
    [DpvFootnote.SecondaryNotRecognizedSecondaryIsRequired]: 'SecondaryNotRecognizedSecondaryIsRequired',
    [DpvFootnote.MilitaryOrDiplomaticAddress]: 'MilitaryOrDiplomaticAddress',
    [DpvFootnote.GeneralDeliveryAddress]: 'GeneralDeliveryAddress',
    [DpvFootnote.PrimaryNumberIsMissing]: 'PrimaryNumberIsMissing',
    [DpvFootnote.PrimaryNumberIsInvalid]: 'PrimaryNumberIsInvalid',
    [DpvFootnote.MissingRequiredSecondary]: 'MissingRequiredSecondary',
    [DpvFootnote.PoBoxStyleAddress]: 'PoBoxStyleAddress',
    [DpvFootnote.PoBoxNumberMissing]: 'PoBoxNumberMissing',
    [DpvFootnote.PoBoxNumberInvalid]: 'PoBoxNumberInvalid',
    [DpvFootnote.ConfirmedWithPrivateMailboxInfo]: 'ConfirmedWithPrivateMailboxInfo',
    [DpvFootnote.ConfirmedWithoutPrivateMailboxInfo]: 'ConfirmedWithoutPrivateMailboxInfo',
    [DpvFootnote.ValidAddressThatDoesNotRecieveUspsDelivery]: 'ValidAddressThatDoesNotRecieveUspsDelivery',
    [DpvFootnote.PrimaryNumberMatchedByDroppingTrailingAlpha]: 'PrimaryNumberMatchedByDroppingTrailingAlpha',
    [DpvFootnote.UniqueZipCode]: 'UniqueZipCode',
};

export enum SmartyFootnote {
    CorrectedZipCode = 'A#',
    CorrectedCityStateSpelling = 'B#',
    InvalidCityStateZip = 'C#',
    NoZipPlus4Assigned = 'D#',
    SameZipForMultiple = 'E#',
    AddressNotFound = 'F#',
    UsedAddresseeData = 'G#',
    MissingSecondaryNumber = 'H#',
    InsufficientAddressData = 'I#',
    DualAddress = 'J#',
    CardinalRuleMatch = 'K#',
    ChangedAddressComponent = 'L#',
    FlaggedForLACSLink = 'LL#',
    CorrectedStreetSpelling = 'M#',
    FixedAbbreviations = 'N#',
    MultipleZipPlus4LowestUsed = 'O#',
    BetterAddressExists = 'P#',
    UniqueZipMatch = 'Q#',
    NoMatchNowEWSMatchSoon = 'R#',
    UnrecognizedSecondary = 'S#',
    MagnetStreetSyndrome = 'T#',
    UnofficialCityName = 'U#',
    UnverifiableCitySTate = 'V#',
    InvalidDeliveryAddress = 'W#',
    DefaultUniqueZipCode = 'X#',
    MilitaryMatch = 'Y#',
    MatchedWithZIPMOVE = 'Z#',
}

export const SmartyFootnoteNames: { [key in SmartyFootnote]: string } = {
    [SmartyFootnote.CorrectedZipCode]: 'CorrectedZipCode',
    [SmartyFootnote.CorrectedCityStateSpelling]: 'CorrectedCityStateSpelling',
    [SmartyFootnote.InvalidCityStateZip]: 'InvalidCityStateZip',
    [SmartyFootnote.NoZipPlus4Assigned]: 'NoZipPlus4Assigned',
    [SmartyFootnote.SameZipForMultiple]: 'SameZipForMultiple',
    [SmartyFootnote.AddressNotFound]: 'AddressNotFound',
    [SmartyFootnote.UsedAddresseeData]: 'UsedAddresseeData',
    [SmartyFootnote.MissingSecondaryNumber]: 'MissingSecondaryNumber',
    [SmartyFootnote.InsufficientAddressData]: 'InsufficientAddressData',
    [SmartyFootnote.DualAddress]: 'DualAddress',
    [SmartyFootnote.CardinalRuleMatch]: 'CardinalRuleMatch',
    [SmartyFootnote.ChangedAddressComponent]: 'ChangedAddressComponent',
    [SmartyFootnote.FlaggedForLACSLink]: 'FlaggedForLACSLink',
    [SmartyFootnote.CorrectedStreetSpelling]: 'CorrectedStreetSpelling',
    [SmartyFootnote.FixedAbbreviations]: 'FixedAbbreviations',
    [SmartyFootnote.MultipleZipPlus4LowestUsed]: 'MultipleZipPlus4LowestUsed',
    [SmartyFootnote.BetterAddressExists]: 'BetterAddressExists',
    [SmartyFootnote.UniqueZipMatch]: 'UniqueZipMatch',
    [SmartyFootnote.NoMatchNowEWSMatchSoon]: 'NoMatchNowEWSMatchSoon',
    [SmartyFootnote.UnrecognizedSecondary]: 'UnrecognizedSecondary',
    [SmartyFootnote.MagnetStreetSyndrome]: 'MagnetStreetSyndrome',
    [SmartyFootnote.UnofficialCityName]: 'UnofficialCityName',
    [SmartyFootnote.UnverifiableCitySTate]: 'UnverifiableCitySTate',
    [SmartyFootnote.InvalidDeliveryAddress]: 'InvalidDeliveryAddress',
    [SmartyFootnote.DefaultUniqueZipCode]: 'DefaultUniqueZipCode',
    [SmartyFootnote.MilitaryMatch]: 'MilitaryMatch',
    [SmartyFootnote.MatchedWithZIPMOVE]: 'MatchedWithZIPMOVE',
};

export const SmartyFootnoteDebugDescriptions: { [key in SmartyFootnote]: string } = {
    [SmartyFootnote.CorrectedZipCode]: 'The address was found to have a different 5-digit ZIP code than the one you provided. The correct ZIP code is shown in the standardized address.',
    [SmartyFootnote.CorrectedCityStateSpelling]: 'The spelling of the city name and/or state abbreviation in the submitted address was found to be different than the standard spelling. The standard spellings are shown in the city_name and state_abbreviation fields.',
    [SmartyFootnote.InvalidCityStateZip]: 'The ZIP Code in the submitted address could not be found because neither a valid city and state, nor valid 5-digit ZIP Code was present. Smarty recommends that the customer check the accuracy of the submitted address.',
    [SmartyFootnote.NoZipPlus4Assigned]: 'This address is not present in the USPS data. Smarty recommends that the customer check the accuracy of the submitted address.',
    [SmartyFootnote.SameZipForMultiple]: 'Multiple records were returned, with the same 5-digit ZIP Code.',
    [SmartyFootnote.AddressNotFound]: 'The address, exactly as submitted, could not be found in the city, state, or ZIP Code provided. Either the primary number is missing, the street is missing, or the street is too badly misspelled to understand.',
    [SmartyFootnote.UsedAddresseeData]: 'Information in the addressee input field was determined to be part of the address. It was moved out of the addressee field and incorporated into the street field.',
    [SmartyFootnote.MissingSecondaryNumber]: 'The address as submitted is missing a secondary number (apartment, suite, etc.). Smarty recommends that the customer check the accuracy of the submitted address and add the missing secondary number to ensure the correct Delivery Point Barcode (DPBC).',
    [SmartyFootnote.InsufficientAddressData]: 'More than one ZIP+4 Code was found to satisfy the address as submitted. The submitted address did not contain sufficiently complete or correct data to determine a single ZIP+4 Code. Smarty recommends that the customer check the accuracy and completeness of the submitted address. For example, a street may have a similar address at both the north and south ends of the street.',
    [SmartyFootnote.DualAddress]: 'The input contained two addresses. For example: 123 MAIN ST PO BOX 99.',
    [SmartyFootnote.CardinalRuleMatch]: 'Although the address as submitted is not valid, we were able to find a match by changing the cardinal direction (North, South, East, West). The cardinal direction we used to find a match is found in the components.',
    [SmartyFootnote.ChangedAddressComponent]: 'An address component (i.e., directional or suffix only) was added, changed, or deleted in order to achieve a match.',
    [SmartyFootnote.FlaggedForLACSLink]: 'The input address matched a record that was LACS-indicated, that was submitted to LACSLink for processing. This does not mean that the address was converted; it only means that the address was submitted to LACSLink because the input address had the LACS indicator set.',
    [SmartyFootnote.CorrectedStreetSpelling]: 'The spelling of the street name was changed in order to achieve a match.',
    [SmartyFootnote.FixedAbbreviations]: 'The delivery address was standardized. For example, if STREET was in the delivery address, Smarty will return ST as its standard spelling.',
    [SmartyFootnote.MultipleZipPlus4LowestUsed]: 'More than one ZIP+4 Code was found to satisfy the address as submitted. The lowest ZIP+4 add-on may be used to break the tie between the records.',
    [SmartyFootnote.BetterAddressExists]: 'The delivery address is matchable, but it is known by another (preferred) name. For example, in New York, NY, AVENUE OF THE AMERICAS is also known as 6TH AVE. An inquiry using a delivery address of 39 6th Avenue would be flagged with Footnote P#. If the given address is acceptable, then it will not be changed to the preferred version (e.g., 7202 Panam Expy S San Antonio TX 78224). If the given address is unacceptable, then it will be changed to the preferred version (e.g., 131 Stone Farm Lebanon NH 03766).',
    [SmartyFootnote.UniqueZipMatch]: 'The address has a "unique" ZIP Code.',
    [SmartyFootnote.NoMatchNowEWSMatchSoon]: 'The delivery address is not yet matchable, but the US Postal Service Early Warning System file indicates that a match will be available soon.',
    [SmartyFootnote.UnrecognizedSecondary]: 'The secondary information (apartment, suite, etc.) was not recognized as part of the USPS data.',
    [SmartyFootnote.MagnetStreetSyndrome]: 'The search resulted in a single response; however, the record matched was flagged as having magnet street syndrome, and the input street name components (pre-directional, primary street name, post-directional, and suffix) did not exactly match those of the record. A "magnet street" is one having a primary street name that is also a suffix or directional word, having either a post-directional or a suffix (i.e., 2220 PARK MEMPHIS TN logically matches to a ZIP+4 record 2200-2258 PARK AVE MEMPHIS TN 38114-6610), but the input address lacks the suffix "AVE" which is present on the ZIP+4 record. The primary street name "PARK" is a suffix word. The record has either a suffix or a post-directional present. Therefore, in accordance with CASS requirements, a ZIP+4 Code must not be returned. The multiple response return code is given since a "no match" would prevent the best candidate.',
    [SmartyFootnote.UnofficialCityName]: 'The city name in the submitted address is an alternate city name that is not accepted by the US Postal Service. The preferred city name is output in the city_name field.',
    [SmartyFootnote.UnverifiableCitySTate]: 'The city and state in the submitted address could not be verified as corresponding to the given 5-digit ZIP Code. This comment does not necessarily denote an error; however, Smarty recommends that the customer check the accuracy of the city and state in the submitted address.',
    [SmartyFootnote.InvalidDeliveryAddress]: 'The USPS does not provide street delivery service for this ZIP Code. The USPS requires the use of a PO Box, General Delivery, or Postmaster for delivery within this ZIP Code.',
    [SmartyFootnote.DefaultUniqueZipCode]: 'The address has a "unique" ZIP Code with a default ZIP+4 code.',
    [SmartyFootnote.MilitaryMatch]: 'The address has a military or diplomatic ZIP Code.',
    [SmartyFootnote.MatchedWithZIPMOVE]: 'The ZIPMOVE product shows which ZIP+4 records have moved from one ZIP Code to another. If an input address matches a ZIP+4 record which the ZIPMOVE product indicates has moved, the search is performed again in the new ZIP Code.',
};
